### ISSUE TITLE
decode or wtf gay shit error

### ISSUE THREAD

**Issue by xhuloo** [xhuloo/discordpy-token-generator#2]
Error: UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 82: character maps to <undefined>

if ur having this error replace ur username.txt file with different usernames.

**Comment by Its-Vichy** [comment]
Dumbass can't even handle utf8 and error 😆😆

**Comment by xhuloo** [comment]
> Dumbass can't even handle utf8 and error 😆😆

🤷🏽

**Comment by xhuloo** [comment]
im on vacation im so i cant update it

**Comment by shahzain345** [comment]
`py -Xutf8 main.py` 😄

**Comment by xhuloo** [comment]
> `py -Xutf8 main.py` 😄

yes qt
