### ISSUE TITLE
v

### ISSUE THREAD

**Issue by cerniq** [xhuloo/discordpy-token-generator#3]
![image](https://user-images.githubusercontent.com/15178702/182010123-8e5be887-eeda-4906-a64c-de0ef3b21786.png)

**Comment by xhuloo** [comment]
change usernames in username.txt to new usernames

**Comment by cerniq** [comment]
worked but now im catching these exceptions 
![image](https://user-images.githubusercontent.com/15178702/182040638-b97c4fdb-b601-47be-97a1-2b965f9d4acf.png)

**Comment by cerniq** [comment]
worked but now im getting this error (ive already tried turning off firewall)
![image](https://user-images.githubusercontent.com/15178702/182040740-2ff1b50b-6727-45df-b3b2-33b7544cfd77.png)

**Comment by xhuloo** [comment]
did u put on proxyless in ur config.json?

**Comment by lkeld** [comment]
I got the same error, i'm using proxies from iproyal
![image](https://user-images.githubusercontent.com/48638597/182072999-10baaa64-644f-458c-85e2-7089d1a09516.png)

**Comment by xhuloo** [comment]
> I got the same error, i'm using proxies from iproyal ![image](https://user-images.githubusercontent.com/48638597/182072999-10baaa64-644f-458c-85e2-7089d1a09516.png)

did u turn off proxyless?

**Comment by lkeld** [comment]
> > I got the same error, i'm using proxies from iproyal ![image](https://user-images.githubusercontent.com/48638597/182072999-10baaa64-644f-458c-85e2-7089d1a09516.png)
> 
> did u turn off proxyless?

Yes I did turn off proxyless

**Comment by xhuloo** [comment]
> > > I got the same error, i'm using proxies from iproyal ![image](https://user-images.githubusercontent.com/48638597/182072999-10baaa64-644f-458c-85e2-7089d1a09516.png)
> > 
> > 
> > did u turn off proxyless?
> 
> Yes I did turn off proxyless

most likely ur proxies, did u put ur proxies in the .txt file?

**Comment by lkeld** [comment]
> > > > I got the same error, i'm using proxies from iproyal ![image](https://user-images.githubusercontent.com/48638597/182072999-10baaa64-644f-458c-85e2-7089d1a09516.png)
> > > 
> > > 
> > > did u turn off proxyless?
> > 
> > 
> > Yes I did turn off proxyless
> 
> most likely ur proxies, did u put ur proxies in the .txt file?

yes i did, the proxies are from iproyal so it might be the format of the proxy, i doubt it is the proxy itself as they are residential.

**Comment by xhuloo** [comment]
> > > > > I got the same error, i'm using proxies from iproyal ![image](https://user-images.githubusercontent.com/48638597/182072999-10baaa64-644f-458c-85e2-7089d1a09516.png)
> > > > 
> > > > 
> > > > did u turn off proxyless?
> > > 
> > > 
> > > Yes I did turn off proxyless
> > 
> > 
> > most likely ur proxies, did u put ur proxies in the .txt file?
> 
> yes i did, the proxies are from iproyal so it might be the format of the proxy, i doubt it is the proxy itself as they are residential.

whats ur format

**Comment by lkeld** [comment]
> > > > > > I got the same error, i'm using proxies from iproyal ![image](https://user-images.githubusercontent.com/48638597/182072999-10baaa64-644f-458c-85e2-7089d1a09516.png)
> > > > > 
> > > > > 
> > > > > did u turn off proxyless?
> > > > 
> > > > 
> > > > Yes I did turn off proxyless
> > > 
> > > 
> > > most likely ur proxies, did u put ur proxies in the .txt file?
> > 
> > 
> > yes i did, the proxies are from iproyal so it might be the format of the proxy, i doubt it is the proxy itself as they are residential.
> 
> whats ur format

There are 4 different options, the one that i was using was user:pass@host:port

**Comment by lkeld** [comment]
> > > > > > > > I got the same error, i'm using proxies from iproyal ![image](https://user-images.githubusercontent.com/48638597/182072999-10baaa64-644f-458c-85e2-7089d1a09516.png)
> > > > > > > 
> > > > > > > 
> > > > > > > did u turn off proxyless?
> > > > > > 
> > > > > > 
> > > > > > Yes I did turn off proxyless
> > > > > 
> > > > > 
> > > > > most likely ur proxies, did u put ur proxies in the .txt file?
> > > > 
> > > > 
> > > > yes i did, the proxies are from iproyal so it might be the format of the proxy, i doubt it is the proxy itself as they are residential.
> > > 
> > > 
> > > whats ur format
> > 
> > 
> > There are 4 different options, the one that i was using was user:pass@host:port
> 
> its suppose be user:pass:port

same issue using proxies in user:pass:hostname:port

![image](https://user-images.githubusercontent.com/48638597/182117936-0ad04b64-76c5-41f9-badc-0985bcfc072b.png)

**Comment by CoolDragon12346** [comment]
It needs a captcha solver. DM me to buy my API:
CoolDragon12346#0403

**Comment by lkeld** [comment]
> It needs a captcha solver. DM me to buy my API: CoolDragon12346#0403

proxy errors not captcha errors, no one gonna buy your scam of a captcha solver.

**Comment by CoolDragon12346** [comment]
Its not a scam. Just dm me and i'll show u

**Comment by lkeld** [comment]
> Its not a scam. Just dm me and i'll show u

ong you should give me a vouch copy and ill believe you

**Comment by CoolDragon12346** [comment]
Im not giving u a copy of my solver, but i an lend u an api
