### ISSUE TITLE
Skidded LOL

### ISSUE THREAD

**Issue by Pr0t0ns** [xhuloo/discordpy-token-generator#6]
Skidded all his REPOS he even hit his goal and didn't release solver xd. He has been exposed many times for skidding he will just close this ticket and play it off and say he made it.

**Comment by xhuloo** [comment]
> Skidded all his REPOS he even hit his goal and didn't release solver xd. He has been exposed many times for skidding he will just close this ticket and play it off and say he made it.

i never said i made it if u cant read it clearly says "Credit: Shahzain" now hop off dick buster

**Comment by xhuloo** [comment]
> > Skidded all his REPOS he even hit his goal and didn't release solver xd. He has been exposed many times for skidding he will just close this ticket and play it off and say he made it.
> 
> i never said i made it if u cant read it clearly says "Credit: Shahzain" now hop off dick buster

and im not releasing it anymore because, personal reaons but if shahzain doesnt respond less then 48 hours then yes ill leak it

**Comment by Pr0t0ns** [comment]
> > Skidded all his REPOS he even hit his goal and didn't release solver xd. He has been exposed many times for skidding he will just close this ticket and play it off and say he made it.
> 
> i never said i made it if u cant read it clearly says "Credit: Shahzain" now hop off dick buster

You where claiming you made this on discord, same with Space Solver, SpaceX Gen, etc.. XD Just stop skidding it's not that hard
